Aded how to enable the neat proxy and a debug message if unounting fails

diff --git a/core/usr/bin/monroe-sync-experiments b/core/usr/bin/monroe-sync-experiments
--- a/core/usr/bin/monroe-sync-experiments
+++ b/core/usr/bin/monroe-sync-experiments
@@ -92,8 +92,8 @@ for SCHEDID in $(experiments -a); do
       echo -n "All files synched, will delete the following files and directories..."
       echo -n "$(find $_EXPPATH -print)"
       # any other file should be rsynced by now
-      umount $_EXPPATH || true
-      rm -rf $_EXPPATH 
+      umount $_EXPPATH || echo -n "Umount of $_EXPPATH failed"
+      rm -rf $_EXPPATH
 
       if (systemctl -q is-active marvind.service); then
         echo "Monroe Scheduler is running keep .traffic and .status"
